# Generated by Django 4.2.7 on 2023-11-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvwizard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
