# Generated by Django 4.2.7 on 2023-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvwizard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='名字'),
        ),
    ]
