# Generated by Django 4.2.7 on 2023-11-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvwizard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users_hoge',
        ),
    ]
